name: License Check

on: [push, pull_request]

jobs:
  style-type-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install click
    - name: Style and type checks
      run: |
    - name: Check license headers
      run: python .devtools/license check src
